"""Deterministic Singapore PII detectors, ported from structured_deidentification.

Source of truth: ``app/R/detect_r.R`` (``se_nric_valid``, ``se_parse_compact_date``,
``se_detectors``, ``se_luhn``, ``se_scan_text``, ``se_dedup_overlaps``, ``se_classify_value``).
Behaviour is pinned by ``tests/parity/r_expected.json``, generated by running the R code itself
(``tests/parity/dump_r.R``). Change the R side first, regenerate, then follow here.

Span records use the R contract: ``start`` is 1-based, ``end`` is inclusive (so ``end`` equals a
Python exclusive end), and ``text[start - 1:end] == match``.

Regex notes: R runs PCRE with ``perl=TRUE, ignore.case=TRUE`` and no UCP, so ``\\b``, ``\\s`` and
``\\w`` are ASCII-only. ``re.ASCII | re.IGNORECASE`` reproduces that.
"""

from __future__ import annotations

import datetime as _dt
import re
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass

_FLAGS = re.ASCII | re.IGNORECASE
_R_WS = " \t\r\n"  # R trimws() default whitespace

# --- Singapore NRIC / FIN check digit ------------------------------------------------------
# Weights 2,7,6,5,4,3,2 over the 7 digits; +4 for T/G, +3 for M; lookup by series.

_NRIC_SHAPE = re.compile(r"^[STFGM][0-9]{7}[A-Z]$")
_NRIC_WEIGHTS = (2, 7, 6, 5, 4, 3, 2)
_ST = "JZIHGFEDCBA"
_FG = "XWUTRQPNMLK"
_M = "KLJNPQRTUWX"


def nric_valid(x: str | None) -> bool:
    """True if ``x`` is an NRIC/FIN whose check letter is correct (S/T/F/G exact, M best-effort)."""
    if x is None:
        return False
    x = str(x).strip(_R_WS).upper()
    if not _NRIC_SHAPE.match(x):
        return False
    prefix, chk = x[0], x[8]
    total = sum(int(d) * w for d, w in zip(x[1:8], _NRIC_WEIGHTS, strict=True))
    if prefix in "TG":
        total += 4
    elif prefix == "M":
        total += 3
    r = total % 11
    if prefix in "ST":
        expected = _ST[r]
    elif prefix in "FG":
        expected = _FG[r]
    else:
        expected = _M[10 - r]
    return chk == expected


# --- compact (separator-less) date ----------------------------------------------------------
# Exactly 8 digits, optionally followed by " HHMMSS" / "THHMMSS" (DICOM / ECG-XML forms).
# Tried as yyyymmdd, then ddmmyyyy, then mmddyyyy; the year must be 1900-2100. The time
# separator is case-sensitive here (R validates with a case-sensitive regexec).

_COMPACT = re.compile(r"^([0-9]{8})(?:[ T][0-9]{6})?$", re.ASCII)
_COMPACT_ORDERS = ((0, 4, 6), (4, 2, 0), (4, 0, 2))  # offsets of (year, month, day)


def parse_compact_date(s: str | None) -> _dt.date | None:
    """Parse an 8-digit (optionally +time) run as a calendar date, or return None."""
    if s is None:
        return None
    m = _COMPACT.match(str(s).strip(_R_WS))
    if not m:
        return None
    d8 = m.group(1)
    for yo, mo, do in _COMPACT_ORDERS:
        year = int(d8[yo:yo + 4])
        try:
            date = _dt.date(year, int(d8[mo:mo + 2]), int(d8[do:do + 2]))
        except ValueError:
            continue
        if 1900 <= year <= 2100:
            return date
    return None


def luhn(num: str) -> bool:
    """Luhn check over the digits of ``num``; fewer than 12 digits is never valid."""
    digits = [int(c) for c in num if c.isascii() and c.isdigit()]
    if len(digits) < 12:
        return False
    total = 0
    for i, d in enumerate(reversed(digits)):
        if i % 2 == 1:
            d *= 2
            if d > 9:
                d -= 9
        total += d
    return total % 10 == 0


def _ip_valid(m: str) -> bool:
    return all(0 <= int(o) <= 255 for o in m.split("."))


# --- detector registry ---------------------------------------------------------------------


@dataclass(frozen=True)
class Detector:
    name: str
    type: str
    identifier: str
    pattern: str
    validate: Callable[[str], bool] | None
    base_conf: float

    @property
    def regex(self) -> re.Pattern[str]:
        return _compile(self.pattern)

    @property
    def anchored(self) -> re.Pattern[str]:
        return _compile(f"^(?:{self.pattern})$")


_CACHE: dict[str, re.Pattern[str]] = {}


def _compile(pattern: str) -> re.Pattern[str]:
    rx = _CACHE.get(pattern)
    if rx is None:
        rx = _CACHE[pattern] = re.compile(pattern, _FLAGS)
    return rx


_SHIPPED: tuple[Detector, ...] = (
    Detector("nric", "nric", "national_id",
             r"\b[STFGMstfgm][0-9]{7}[A-Za-z]\b", nric_valid, 0.6),
    # Hospital temporary IC: X/Y + 7 or 10 digits + letter. No published check digit.
    Detector("temp_ic", "nric", "national_id",
             r"\b[XYxy][0-9]{7}(?:[0-9]{3})?[A-Za-z]\b", None, 0.8),
    Detector("email", "email", "email",
             r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b", None, 0.97),
    Detector("phone", "phone", "phone",
             r"(?<![0-9])(?:\+?65[ -]?)?[3689][0-9]{3}[ -]?[0-9]{4}(?![0-9])", None, 0.7),
    Detector("postal", "postal", "postal_code",
             r"\bSingapore\s+[0-9]{6}\b|\bS\(?[0-9]{6}\)?\b", None, 0.6),
    Detector("date", "date", "dob",
             r"\b(?:[0-3]?[0-9][/-][0-1]?[0-9][/-](?:19|20)[0-9]{2}"
             r"|(?:19|20)[0-9]{2}[/-][0-1]?[0-9][/-][0-3]?[0-9])\b", None, 0.75),
    Detector("date_compact", "date", "dob",
             r"\b[0-9]{8}(?:[ T][0-9]{6})?\b",
             lambda m: parse_compact_date(m) is not None, 0.55),
    Detector("url", "url", "other_id", r"\bhttps?://[^\s]+\b", None, 0.95),
    Detector("ip", "ip", "other_id", r"\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b", _ip_valid, 0.7),
    # Generic passport: 1-2 letters + 6-8 digits (loose, low confidence).
    Detector("passport", "passport", "national_id", r"\b[A-Za-z]{1,2}[0-9]{6,8}\b", None, 0.35),
    # SG admission / case number: 10 digits + trailing letter.
    Detector("case", "case", "case_visit", r"\b[0-9]{10}[A-Za-z]\b", None, 0.7),
    Detector("mrn", "mrn", "mrn", r"\b[A-Za-z]{0,3}[0-9]{6,10}\b", None, 0.4),
    Detector("creditcard", "account", "other_id", r"\b(?:[0-9]{4}[ -]?){3}[0-9]{4}\b",
             lambda m: luhn(m.replace(" ", "").replace("-", "")), 0.6),
)

# Opt-in bare 6-digit postal code: ambiguous, so it goes last and scores 0.5 (above mrn's 0.4).
_POSTAL6 = Detector("postal6", "postal", "postal_code", r"\b[0-9]{6}\b", None, 0.5)


def detectors(postal6: bool = False, extra: Iterable[Detector] = ()) -> dict[str, Detector]:
    """The shipped detector set in R order, plus optional ``postal6`` and ``extra`` detectors."""
    out = {d.name: d for d in _SHIPPED}
    if postal6:
        out[_POSTAL6.name] = _POSTAL6
    for d in extra:
        out[d.name] = d
    return out


# --- scanning ------------------------------------------------------------------------------


def _validated_conf(d: Detector, s: str, floor: bool) -> float:
    if d.validate is None:
        return d.base_conf
    try:
        ok = bool(d.validate(s))
    except Exception:  # a validator error is a failed validation, as in R's tryCatch
        ok = False
    if ok:
        return 0.99
    return max(0.1, d.base_conf - 0.4) if floor else d.base_conf - 0.4


def scan_text(text: str | None, dets: Mapping[str, Detector] | None = None) -> list[dict]:
    """All detector hits in ``text`` as span records, grouped by detector in registry order."""
    if not text:
        return []
    dets = detectors() if dets is None else dets
    out: list[dict] = []
    for name, d in dets.items():
        for m in d.regex.finditer(text):
            s = m.group(0)
            out.append({
                "start": m.start() + 1,
                "end": m.end(),
                "match": s,
                "type": d.type,
                "identifier": d.identifier,
                "detector": f"rule:{name}",
                "confidence": _validated_conf(d, s, floor=True),
            })
    return out


def dedup_overlaps(spans: list[dict]) -> list[dict]:
    """Keep the widest (then most confident) span of each overlap cluster."""
    ordered = sorted(spans, key=lambda sp: (-(sp["end"] - sp["start"]), -sp["confidence"]))
    kept: list[dict] = []
    for sp in ordered:
        if not any(sp["start"] <= k["end"] and sp["end"] >= k["start"] for k in kept):
            kept.append(sp)
    return kept


def classify_value(value: str | None, dets: Mapping[str, Detector] | None = None
                   ) -> dict[str, float]:
    """Whole-value (anchored) detector hits for one cell: ``{detector_name: confidence}``."""
    if value is None:
        return {}
    v = str(value).strip(_R_WS)
    if not v:
        return {}
    dets = detectors() if dets is None else dets
    return {name: _validated_conf(d, v, floor=False)
            for name, d in dets.items() if d.anchored.search(v)}
